title: Figma Introduction
remote_theme: pmarsceill/just-the-docs

# "Edit this page on GitHub" link
gh_edit_repository: "https://github.com/chiragvijaykumar/figma-intro"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_branch: "master"   # change to "main" if your default branch is main
gh_edit_view_mode: "tree"  # "tree" or "edit"

# License info (used across workshop)
license_name: "Creative Commons Attribution 4.0 International License"
license_url: "https://creativecommons.org/licenses/by/4.0/"
license_image_url: "https://i.creativecommons.org/l/by/4.0/88x31.png"

# Top-right links
aux_links:
  "UVic Libraries Digital Scholarship Commons":
    - "https://lib.uvic.ca/dsc"
aux_links_new_tab: true

# Footer
back_to_top: true
back_to_top_text: "Back to top"

footer_content: >-
  <img src="https://i.creativecommons.org/l/by/4.0/88x31.png" style="float:right;">
  Copyright &copy; 2023â€“{{ site.time | date: '%Y' }}
  <a href="https://uvic.ca/library/dsc/">UVic Libraries Digital Scholarship Commons</a> -
  <a href="mailto:dscommons@uvic.ca">dscommons@uvic.ca</a>
  <br>View other <a href="https://lib.uvic.ca/curric">DSC workshops</a>
  <br>Distributed under a
  <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Google Analytics
ga_tracking: G-J1P4V8MFWB
ga_tracking_anonymize_ip: true

plugins:
  - jekyll-seo-tag
